---
title: "Young People Survey Cleaning"
author: "Adina Zhang"
date: "April 26, 2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(lattice)
library(caret)
library(corrplot)
library(ggplot2)
library(ggpubr)
library(AppliedPredictiveModeling)
```

```{r}
survey = read_csv("responses.csv") %>% janitor::clean_names()
names(survey)

#List Predictors and Outcome of Interest
vars <-c(#Predictors
  "metal_or_hardrock", "punk", "horror", "thriller", "war", "action",
  "countryside_outdoors", "active_sport", "adrenaline_sports", "cars",
  "fear_of_public_speaking",
  "smoking", "alcohol",
  "criminal_damage", "cheating_in_school", "small_big_dogs", "prioritising_workload","assertiveness", "parents_advice",
         #Outcome
         "gender")

#Subset Data
survey_new <-survey[vars] 

#Recoding Data
survey_new$gender <- recode(survey_new$gender, "male" = 1, "female" = 0)

survey_new$alcohol <- recode(survey_new$alcohol, "drink a lot" = 2, "social drinker" = 1, "never" = 0)

survey_new$smoking <- recode(survey_new$smoking, "never smoked" = 0, "former smoker" = 2, "tried smoking" = 3, "current smoker" = 4)

#Count Missing Entries
sapply(survey_new, function(x)sum(is.na(survey_new))) %>% print()
```

#EDA
```{r eda}
eda <-survey_new %>% na.omit() 

# matrix of predictors 
x  <- eda
x$gender <- NULL

#matrix predictors with dummy variables
x_dummy <-model.matrix(gender~.,eda)[,-1]

# vector of response
y <- eda$gender 

cor(x) %>% corrplot()

```

#Histograms/Distributions of Predictors and Outcomes

```{r}
#Integer to Categorical Variable
eda$gender2 <-as.factor(eda$gender)
levels(eda$gender2) <-c("female", "male")

plot2 <-ggplot(eda, aes(x=metal_or_hardrock, fill=gender2)) +
    geom_histogram(binwidth=1, color="black") + labs(x = "Metal/Hardrock") + theme(axis.title.x=element_text(size=6))

plot3 <-ggplot(eda, aes(x=punk, fill=gender2)) +
    geom_histogram(binwidth=1, colour="black") + theme(axis.title.x=element_text(size=6))

plot4 <-ggplot(eda, aes(x=horror, fill=gender2)) +
    geom_histogram(binwidth=1, colour="black") + theme(axis.title.x=element_text(size=6))

plot5 <-ggplot(eda, aes(x=thriller, fill=gender2)) +
    geom_histogram(binwidth=1, colour="black") + theme(axis.title.x=element_text(size=6))

plot6 <-ggplot(eda, aes(x=war, fill=gender2)) +
    geom_histogram(binwidth=1, colour="black") + theme(axis.title.x=element_text(size=6))

plot7 <-ggplot(eda, aes(x=action, fill=gender2)) +
    geom_histogram(binwidth=1, colour="black") + theme(axis.title.x=element_text(size=6))

plot8 <-ggplot(eda, aes(x=countryside_outdoors, fill=gender2)) +
    geom_histogram(binwidth=1, colour="black") + labs(x = "Outdoors") + theme(axis.title.x=element_text(size=6))

plot9 <-ggplot(eda, aes(x=active_sport, fill=gender2)) +
    geom_histogram(binwidth=1, colour="black") + theme(axis.title.x=element_text(size=6))

plot10 <-ggplot(eda, aes(x=adrenaline_sports, fill=gender2)) +
    geom_histogram(binwidth=1, colour="black") + theme(axis.title.x=element_text(size=6))

plot11 <-ggplot(eda, aes(x=cars, fill=gender2)) +
    geom_histogram(binwidth=1, colour="black") + theme(axis.title.x=element_text(size=6))

plot12 <-ggplot(eda, aes(x=fear_of_public_speaking, fill=gender2)) +
    geom_histogram(binwidth=1, colour="black") + labs(x = "Public Speaking") + theme(axis.title.x=element_text(size=6))

plot13 <-ggplot(eda, aes(x=smoking, fill=gender2)) +
    geom_histogram(binwidth=1, colour="black") + theme(axis.title.x=element_text(size=6))

plot14 <-ggplot(eda, aes(x=alcohol, fill=gender2)) +
    geom_histogram(binwidth=1, colour="black") + theme(axis.title.x=element_text(size=6))

plot15 <-ggplot(eda, aes(x=criminal_damage, fill=gender2)) +
    geom_histogram(binwidth=1, colour="black") + theme(axis.title.x=element_text(size=6))

plot16 <-ggplot(eda, aes(x=cheating_in_school, fill=gender2)) +
    geom_histogram(binwidth=1, colour="black") + labs(x = "Cheating") + theme(axis.title.x=element_text(size=6))

plot17 <-ggplot(eda, aes(x=small_big_dogs, fill=gender2)) +
    geom_histogram(binwidth=1, colour="black") + labs(x = "Dangerous Dogs") + theme(axis.title.x=element_text(size=6))

plot18 <-ggplot(eda, aes(x=prioritising_workload, fill=gender2)) +
    geom_histogram(binwidth=1, colour="black") + theme(axis.title.x=element_text(size=6))

plot19 <-ggplot(eda, aes(x=assertiveness, fill=gender2)) +
    geom_histogram(binwidth=1, colour="black") + theme(axis.title.x=element_text(size=6))

plot20 <-ggplot(eda, aes(x=parents_advice, fill=gender2)) +
    geom_histogram(binwidth=1, colour="black") + theme(axis.title.x=element_text(size=6))

#plot1, plot2, plot3, plot4, plot5, plot6, plot7, plot8, plot9, plot10,
# plot11, plot12, plot13, plot14, plot15, plot16, plot17, plot18, plot19, plot20
```


```{r}

ggarrange(plot2, plot3, plot4, plot5, plot6, plot7, plot8, plot9, plot10, plot11, plot12, plot13, plot14, plot15, plot16, plot17, plot18, plot19, plot20, legend = NULL, common.legend=TRUE)

```

#PCA
```{r}
library(factoextra)
eda_pca <-eda
eda_pca$gender2 <-NULL

pca <- prcomp(eda_pca)
pca$rotation

fviz_pca_biplot(pca, axes = c(1,2), 
                habillage = ifelse(eda_pca$gender==1, "Male","Female"), 
                label = c("var"), addEllipses = TRUE, title="PCA by Gender")

pca$sdev
pca.var =pca$sdev ^2
pve=pca.var/sum(pca.var )
pve
```

```{r}
fviz_contrib(pca, choice = "var", axes = 1) %>% plot()
fviz_contrib(pca, choice = "var", axes = 2) %>% plot()

```


